Tutorial I followed: [link](https://towardsdatascience.com/numpy-essentials-for-data-science-25dc39fae39)

# Installation and Import

In [3]:
# !pip install numpy
import numpy as np

In [5]:
# numpy version (mine is 1.21.1)
np.__version__

'1.21.1'

# Numpy array creation(N-Dimensional)

Unlike python lists, numpy arrays can only have one kind of data type(int, float, strings, etc).
To convert python list to a NumPy array, use np.array() function

In [5]:
l = [5, 8, 9]
np_array = np.array(l)
print(np_array)
print(type(np_array))

[5 8 9]
<class 'numpy.ndarray'>


In [8]:
l2d = [[1,2,3],[4,5,6]]
md_arr = np.array(l2d)
print(md_arr)
print(type(md_arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [15]:
# Create a 2D array of zeros of shape 3×4
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [18]:
# Create an array of evenly spaced values (start, [stop, [step]])
d = np.arange(5)
print(d)

d = np.arange(5, 20)
print(d)

d = np.arange(5, 20, 4)
print(d)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  9 13 17]


In [24]:
# Create an array of evenly spaced values (number of samples)
d = np.linspace(0,10,2)
print(d)

d = np.linspace(0,10,3)
print(d)

d = np.linspace(0,10,4)
print(d)

d = np.linspace(0,10,9)
print(d)

d = np.linspace(0,2,9)
print(d)

[ 0. 10.]
[ 0.  5. 10.]
[ 0.          3.33333333  6.66666667 10.        ]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [30]:
# Create a constant array of sevens of shape 2 × 2
sevens = np.full((2,2),7)
print(sevens)

# Create a constant array of ones of shape 2 × 5
ones = np.full((2,5),1)
print(ones)

[[7 7]
 [7 7]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [31]:
# Create a 2×2 identity matrix
I2 = np.eye(2)
print(I2)

# Create a 4×4 identity matrix
I4 = np.eye(4)
print(I4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## np.random.rand(d0, d1, ..., dn)

In [54]:
# Random values in a given shape.
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a1 = np.random.rand(2)
a2 = np.random.rand(2,3)
a3 = np.random.rand(2,2,3)
b = np.random.rand()
print('a1:')
print(a1)
print('a2:')
print(a2)
print('a3:')
print(a3)
print('b:')
print(b)

a1:
[0.63978286 0.83528408]
a2:
[[0.04035973 0.46938334 0.84465868]
 [0.16110399 0.66537114 0.44208103]]
a3:
[[[0.45600711 0.35374305 0.42502304]
  [0.25437157 0.77483495 0.55992523]]

 [[0.09396547 0.71884635 0.37185489]
  [0.97412541 0.81748204 0.79641078]]]
b:
0.7439367491022363


## np.random.randn(d0, d1, ..., dn)

In [59]:
# Return a sample (or samples) from the “standard normal” distribution.
# A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution,
# or a single such float if no parameters were supplied.
a1 = np.random.randn(2)
a2 = np.random.randn(2,3)
a3 = np.random.randn(2,2,3)
b = np.random.randn()
print('a1:')
print(a1)
print('a2:')
print(a2)
print('a3:')
print(a3)
print('b:')
print(b)

a1:
[-0.59233389 -0.13654059]
a2:
[[-0.03930472 -0.59186681 -0.81329192]
 [ 0.05401774 -0.53543081 -1.26624446]]
a3:
[[[ 1.97841585  0.9360122   1.23330707]
  [ 1.57797902 -1.15692719  1.47630287]]

 [[ 1.19403475 -0.52765218 -0.63772838]
  [ 0.07964992  0.08772296  1.30945911]]]
b:
1.3146345851657093
