Tutorial I followed: [link](https://towardsdatascience.com/numpy-essentials-for-data-science-25dc39fae39)

# Installation and Import

In [2]:
# !pip install numpy
import numpy as np

In [3]:
# numpy version (mine is 1.21.1)
np.__version__

'1.21.6'

# Numpy array creation(N-Dimensional)

Unlike python lists, numpy arrays can only have one kind of data type(int, float, strings, etc).
To convert python list to a NumPy array, use np.array() function

In [4]:
l = [5, 8, 9]
np_array = np.array(l)
print(np_array)
print(type(np_array))

[5 8 9]
<class 'numpy.ndarray'>


In [5]:
l2d = [[1,2,3],[4,5,6]]
md_arr = np.array(l2d)
print(md_arr)
print(type(md_arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
# Create a 2D array of zeros of shape 3×4
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Create an array of evenly spaced values (start, [stop, [step]])
d = np.arange(5)
print(d)

d = np.arange(5, 20)
print(d)

d = np.arange(5, 20, 4)
print(d)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  9 13 17]


In [8]:
# Create an array of evenly spaced values (number of samples)
d = np.linspace(0,10,2)
print(d)

d = np.linspace(0,10,3)
print(d)

d = np.linspace(0,10,4)
print(d)

d = np.linspace(0,10,9)
print(d)

d = np.linspace(0,2,9)
print(d)

[ 0. 10.]
[ 0.  5. 10.]
[ 0.          3.33333333  6.66666667 10.        ]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [9]:
# Create a constant array of sevens of shape 2 × 2
sevens = np.full((2,2),7)
print(sevens)

# Create a constant array of ones of shape 2 × 5
ones = np.full((2,5),1)
print(ones)

[[7 7]
 [7 7]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
# Create a 2×2 identity matrix
I2 = np.eye(2)
print(I2)

# Create a 4×4 identity matrix
I4 = np.eye(4)
print(I4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## np.random.rand(d0, d1, ..., dn)

In [11]:
# Random values in a given shape.
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a1 = np.random.rand(2)
a2 = np.random.rand(2,3)
a3 = np.random.rand(2,2,3)
b = np.random.rand()
print('a1:')
print(a1)
print('a2:')
print(a2)
print('a3:')
print(a3)
print('b:')
print(b)

a1:
[0.2202405  0.78704547]
a2:
[[0.2084212  0.67860123 0.70445231]
 [0.47686864 0.22262105 0.3179326 ]]
a3:
[[[0.11932221 0.51645891 0.68721872]
  [0.27171493 0.31297042 0.18264833]]

 [[0.48950921 0.1556927  0.40795378]
  [0.34277942 0.54298063 0.40031245]]]
b:
0.002333423745939145


## np.random.randn(d0, d1, ..., dn)

In [12]:
# Return a sample (or samples) from the “standard normal” distribution.
# A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution,
# or a single such float if no parameters were supplied.
a1 = np.random.randn(2)
a2 = np.random.randn(2,3)
a3 = np.random.randn(2,2,3)
b = np.random.randn()
print('a1:')
print(a1)
print('a2:')
print(a2)
print('a3:')
print(a3)
print('b:')
print(b)

a1:
[ 0.99693849 -1.4339577 ]
a2:
[[-0.01698086 -0.40885193 -1.14353109]
 [-0.38418481 -1.49904254 -0.10197304]]
a3:
[[[-2.43882992  0.56114558 -0.7249722 ]
  [ 1.30451226 -0.62411416 -0.19738452]]

 [[ 2.04692831  0.90015732 -0.46189553]
  [-1.37624182  1.39143743  1.1861816 ]]]
b:
0.9885294293066418


# Common Attributes

In [13]:
a = np.array([4,4,9])
b = np.array([[4,4,9], [4, -1, 0]])
c = np.array([
                [
                    [4,4,9],
                    [4,1,0]
                ],
                [
                    [1,4,5],
                    [2,1,8]
                ]
             ])
d = np.array(5)

In [14]:
# shape — tells us the shape of the array.
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(3,)
(2, 3)
(2, 2, 3)
()


In [15]:
# len() — returns the length of the array
print(len(a))
print(len(b))
print(len(c))
# print(len(d)) # this doesn't work => TypeError: len() of unsized object

3
2
2


In [16]:
# ndim — returns the array dimension i.e. len(shape)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
2
3
0


In [92]:
# astype() — converts the data type of the values to the specified type
print(a.astype(str))
print(b.astype(str))

['4' '4' '9']
[['4' '4' '9']
 ['4' '-1' '0']]


In [25]:
# dtype — tells us the data type of the values in the array
m = np.array([[4.6, 5], [1, -5.3]])
print(m.dtype)
print(m.astype(str).dtype)

float64
<U32


In [24]:
# size — gives the number of elements in the array.
print(a, a.size)
print(b, b.size)
print(c, c.size)

[4 4 9] 3
[[ 4  4  9]
 [ 4 -1  0]] 6
[[[4 4 9]
  [4 1 0]]

 [[1 4 5]
  [2 1 8]]] 12
